# Motor driver configuration for Cytron MDDRC10
motor_driver:
  ros__parameters:
    # GPIO pin configuration
    rc1_pin: 18                    # Left motor group (GPIO pin)
    rc2_pin: 19                    # Right motor group (GPIO pin)
    
    # PWM configuration
    pwm_frequency: 50              # PWM frequency in Hz (standard for RC)
    
    # Velocity limits
    max_linear_velocity: 1.0       # Maximum linear velocity (m/s)
    max_angular_velocity: 1.0      # Maximum angular velocity (rad/s)
    
    # Safety configuration
    safety_timeout: 1.0            # Stop motors if no command for this many seconds
    
    # Motor calibration (if needed)
    # motor_left_scale: 1.0        # Scale factor for left motor
    # motor_right_scale: 1.0       # Scale factor for right motor