controller_manager:
  ros__parameters:
    update_rate: 50

    diff_drive_base:
      type: diff_drive_controller/DiffDriveController
      publish_rate: 50
      left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
      right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]
      wheel_separation: 0.3
      wheel_radius: 0.05
      use_stamped_vel: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
